all:

test_err: calculator.perl
	./calculator.perl 0 + 0
	./calculator.perl 0 - 0
	./calculator.perl 0 / 0
	./calculator.perl 0 \* 0
	./calculator.perl 0 % 0
	./calculator.perl 0 x^y 0
	./calculator.perl 0 sin
	./calculator.perl 0 cos
	./calculator.perl 0 tan
	./calculator.perl 0 e^x
	./calculator.perl 0 ln
	./calculator.perl -4 sqrt
	./calculator.perl -4 2^x
	./calculator.perl -8 cbrt
	./calculator.perl -3 3^x

test:
	./calculator.perl 0 + 1
	./calculator.perl 0 - 1
	./calculator.perl 0 / 1
	./calculator.perl 0 \* 1
	./calculator.perl 0 % 1
	./calculator.perl 0 x^y 0
	./calculator.perl 0 sin
	./calculator.perl 0 cos
	./calculator.perl 0 tan
	./calculator.perl 0 e^x
	./calculator.perl 0 ln
	./calculator.perl -4 sqrt
	./calculator.perl -4 2^x
	./calculator.perl -8 cbrt
	./calculator.perl -3 3^x
