all:

test: calculator.perl
	./calculator.perl 90 + 1
	./calculator.perl 90 - 1
	./calculator.perl 90 \* 1
	./calculator.perl 90 / 1
	./calculator.perl 90 sin
	./calculator.perl 90 cos
	./calculator.perl 90 tan
	./calculator.perl 90 exp
	./calculator.perl 90 ln
	./calculator.perl 90 sqrt
	./calculator.perl 90 sqr
	./calculator.perl 90 cbrt
	./calculator.perl 90 cube
